/* ------------------------------------------------------------------------------------
-- Tổng hợp dữ liệu từ bảng raw gộp lại tổng hợp nhóm theo các chiều
*/
INSERT INTO dbo.booking_pace_report
SELECT REPORT_DATE, STAYING AS STAYING_DATE, PROPERTY, MARKET, WINDOW, WINDOW_SORT, 
    SUM(N_OF_ROOM) AS TOTAL_ROOM, SUM(ROOM_REV) AS ROOM_REV
FROM
(SELECT *, 
    DATEDIFF(DAY, CREATE_DATE, ARRIVAL) AS WINDOW_DAYS,
    CASE 
        WHEN DATEDIFF(DAY, CREATE_DATE, ARRIVAL) <= 7 THEN '1 WEEK' 
        WHEN DATEDIFF(DAY, CREATE_DATE, ARRIVAL)  <= 14 THEN '2 WEEKS'
        WHEN DATEDIFF(DAY, CREATE_DATE, ARRIVAL)  <= 21 THEN '3 WEEKS'
        WHEN DATEDIFF(DAY, CREATE_DATE, ARRIVAL)  <= 30 THEN '4 WEEKS'
        WHEN DATEDIFF(DAY, CREATE_DATE, ARRIVAL)  <= 60 THEN '1-2 MONTHS'
        WHEN DATEDIFF(DAY, CREATE_DATE, ARRIVAL)  <= 90 THEN '2-3 MONTHS'
        WHEN DATEDIFF(DAY, CREATE_DATE, ARRIVAL)  <= 180 THEN '3-6 MONTHS'
        WHEN DATEDIFF(DAY, CREATE_DATE, ARRIVAL)  <= 365 THEN '6-12 MONTHS'
        ELSE '> 12 MONTHS'
    END AS [WINDOW], 
    CASE 
        WHEN DATEDIFF(DAY, CREATE_DATE, ARRIVAL)  <= 7 THEN 1
        WHEN DATEDIFF(DAY, CREATE_DATE, ARRIVAL)  <= 14 THEN 2
        WHEN DATEDIFF(DAY, CREATE_DATE, ARRIVAL)  <= 21 THEN 3
        WHEN DATEDIFF(DAY, CREATE_DATE, ARRIVAL)  <= 30 THEN 4
        WHEN DATEDIFF(DAY, CREATE_DATE, ARRIVAL)  <= 60 THEN 5
        WHEN DATEDIFF(DAY, CREATE_DATE, ARRIVAL)  <= 90 THEN 6
        WHEN DATEDIFF(DAY, CREATE_DATE, ARRIVAL)  <= 180 THEN 7
        WHEN DATEDIFF(DAY, CREATE_DATE, ARRIVAL)  <= 365 THEN 8
        ELSE 9
    END AS [WINDOW_SORT] 
    FROM dbo.booking_pace_sample_data
) r
GROUP BY REPORT_DATE, STAYING, PROPERTY, MARKET, WINDOW, WINDOW_SORT
ORDER BY REPORT_DATE, STAYING, PROPERTY, MARKET, WINDOW_SORT
