-- DROP TABLE dbo.booking_pace_history
-- TRUNCATE TABLE dbo.booking_pace_history;
CREATE TABLE dbo.booking_pace_history (
    STAY_MONTH NVARCHAR(7),
    PROPERTY NVARCHAR(50),
    ARRIVAL DATE, 
    DEPARTURE DATE,
    STAYING DATE,
    CREATE_DATE DATE,
    MARKET NVARCHAR(20),
    RATE_CODE NVARCHAR(20),
    RATE_AMT FLOAT,
    TOTAL_TURN_OVER DECIMAL(18,2),
    ARR DECIMAL(18,2),
    ROOM_REV DECIMAL(18,2),
    FB_REV DECIMAL(18,2),
    OTHER_REV DECIMAL(18,2),
    STATUS NVARCHAR(20),
    R_TYPE NVARCHAR(20),
    R_CHARGE NVARCHAR(20),
    N_OF_ROOM INT,
    N_OF_ADT INT,
    N_OF_CHD INT,
    BK_SOURCE NVARCHAR(20),
    COUNTRY NVARCHAR(20),
    NATIONALITY NVARCHAR(20), 
    BOOKING BIT,

    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    FILE_NAME NVARCHAR(500)
);

SELECT * 
FROM dbo.booking_pace_history
WHERE PROPERTY = 'SRC'
ORDER BY STAYING DESC

SELECT * 
FROM dbo.booking_pace_actual
WHERE PROPERTY = 'SRC' 
ORDER BY STAYING_DATE DESC


SELECT STAYING
FROM dbo.booking_pace_history 
WHERE STAYING IS NOT NULL
GROUP BY STAYING
ORDER BY STAYING

SELECT PROPERTY, REPORT_DATE, MAX(MODIFIED_AT) AS MODIFIED_AT
FROM dbo.booking_pace_detail
WHERE PROPERTY = 'SRC'
GROUP BY PROPERTY, REPORT_DATE

SELECT PROPERTY, STAYING, MAX(MODIFIED_AT) AS MODIFIED_AT
FROM dbo.booking_pace_history
WHERE PROPERTY = 'SRC'
GROUP BY PROPERTY, STAYING
ORDER BY PROPERTY, STAYING DESC

SELECT PROPERTY, STAYING_DATE, MAX(MODIFIED_AT) AS MODIFIED_AT
FROM dbo.booking_pace_actual
WHERE PROPERTY = 'SRC'
GROUP BY PROPERTY, STAYING_DATE
ORDER BY PROPERTY, STAYING_DATE DESC