-- DROP TABLE dbo.booking_pace_actual
-- TRUNCATE TABLE dbo.booking_pace_acutal
CREATE TABLE dbo.booking_pace_actual (
    STAYING_DATE DATE,
    PROPERTY NVARCHAR(50), 
    MARKET NVARCHAR(20),
    R_TYPE NVARCHAR(20),
    R_CHARGE NVARCHAR(20),
    WINDOW_ID INT,
    TOTAL_ROOM INT,
    ROOM_REV DECIMAL(18,2),
    ARR DECIMAL(18, 2), 
    TOTAL_BOOKING INT,

    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME
)

GO

SELECT *
FROM dbo.booking_pace_actual

SELECT PROPERTY, MIN(STAYING_DATE) AS MIN_DATE, MAX(STAYING_DATE) AS MAX_DATE, COUNT(*) AS NB_ROWS
FROM dbo.booking_pace_actual
GROUP BY PROPERTY
ORDER BY PROPERTY

SELECT PROPERTY, STAYING_DATE, COUNT(*) AS NB_ROWS
FROM dbo.booking_pace_actual
GROUP BY PROPERTY, STAYING_DATE
ORDER BY PROPERTY, STAYING_DATE