SELECT PROPERTY, REPORT_DATE, COUNT(*) AS NB_ROWS
FROM stg.booking_pace_src
GROUP BY PROPERTY, REPORT_DATE
ORDER BY PROPERTY, REPORT_DATE

SELECT PROPERTY, REPORT_DATE, COUNT(*) AS NB_ROWS
FROM stg.booking_pace_scsrpq WITH(NOLOCK)
GROUP BY PROPERTY, REPORT_DATE
ORDER BY PROPERTY, REPORT_DATE

SELECT PROPERTY, REPORT_DATE, COUNT(*) AS NB_ROWS
FROM stg.booking_pace_sbhpq
GROUP BY PROPERTY, REPORT_DATE
ORDER BY PROPERTY, REPORT_DATE

SELECT PROPERTY, REPORT_DATE, COUNT(*) AS NB_ROWS
FROM stg.booking_pace_cpv
GROUP BY PROPERTY, REPORT_DATE
ORDER BY PROPERTY, REPORT_DATE

SELECT PROPERTY, MIN(REPORT_DATE) AS MIN_DATE, MAX(REPORT_DATE) AS MAX_DATE, COUNT(*) AS NB_ROWS
FROM dbo.booking_pace_report
GROUP BY PROPERTY
ORDER BY PROPERTY

SELECT PROPERTY, REPORT_DATE, COUNT(*) AS NB_ROWS
FROM dbo.booking_pace_report
GROUP BY PROPERTY, REPORT_DATE
ORDER BY PROPERTY, REPORT_DATE

SELECT PROPERTY, REPORT_DATE, COUNT(*) AS NB_ROWS
FROM dbo.booking_pace_detail
GROUP BY PROPERTY, REPORT_DATE
ORDER BY PROPERTY, REPORT_DATE

SELECT PROPERTY, STAYING_DATE, COUNT(*) AS NB_ROWS
FROM dbo.booking_pace_actual
GROUP BY PROPERTY, STAYING_DATE
ORDER BY PROPERTY, STAYING_DATE

SELECT PROPERTY, STAYING, COUNT(*) AS NB_ROWS
FROM dbo.booking_pace_history
GROUP BY PROPERTY, STAYING
ORDER BY PROPERTY, STAYING

SELECT * 
FROM stg.exchange_rate
ORDER BY REPORT_DATE, FROM_CURRENCY_CODE, TO_CURRENCY_CODE


/*
DELETE d FROM dbo.booking_pace_detail d WHERE REPORT_DATE = '2025-08-18'
DELETE d FROM dbo.booking_pace_report d WHERE REPORT_DATE = '2025-08-18'

DELETE d FROM dbo.booking_pace_history d WHERE STAYING = '2025-08-17'
DELETE d FROM dbo.booking_pace_actual d WHERE STAYING_DATE = '2025-08-17'

EXEC dbo.sp_fload_booking_pace_detail
EXEC dbo.sp_fload_booking_pace_report

EXEC dbo.sp_iload_booking_pace_detail
EXEC dbo.sp_iload_booking_pace_report
*/