USE bim_report
GO

/* --------------------------------------------------------------------------------- *
Template: 03
Property: Crowne Plaza Vientaine
*/

-- DROP TABLE stg.booking_pace_cpv;
-- TRUNCATE TABLE stg.booking_pace_cpv;
-- DROP TABLE stg.booking_pace_cpv;
DROP TABLE IF EXISTS stg.booking_pace_cpv
CREATE TABLE stg.booking_pace_cpv (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    REPORT_DATE DATE,
    PROPERTY NVARCHAR(50),
    CONSIDERED_DATE DATE,
    ADULTS INT,
    CHILDREN INT,
    CREATED_DATE DATE,
    COUNTRY NVARCHAR(10),
    NO_ROOMS INT,
    MARKET_CODE NVARCHAR(20),
    SOURCE_CODE NVARCHAR(20),
    CHANNEL NVARCHAR(20),
    RATE_CODE NVARCHAR(20),
    ROOM_CAT NVARCHAR(20),
    RTC NVARCHAR(20),
    ARR DATE,
    DEP DATE,
    RESV_NAME_ID INT,
    ROOM_REVENUE DECIMAL(18, 2),
    FOOD_REVENUE DECIMAL(18, 2),
    OTHER_REVENUE DECIMAL(18, 2),
    COMP_ROOM_REVENUE DECIMAL(18, 2),

    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    FILE_NAME NVARCHAR(500)
);

CREATE TABLE stg.booking_pace_opera_01 (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    REPORT_DATE DATE,
    PROPERTY NVARCHAR(50),
    CONSIDERED_DATE DATE,
    ADULTS INT,
    CHILDREN INT,
    CREATED_DATE DATE,
    -- CREATED_USER NVARCHAR(50),
    COUNTRY NVARCHAR(10),
    NO_ROOMS INT,
    -- DEDUCT_YN CHAR(1),
    -- GROUP_YN CHAR(1),
    
    -- RATE_USD FLOAT,
    MARKET_CODE NVARCHAR(20),
    SOURCE_CODE NVARCHAR(20),
    CHANNEL NVARCHAR(20),
    RATE_CODE NVARCHAR(20),
    ROOM_CAT NVARCHAR(20),
    RTC NVARCHAR(20),
    ARR DATE,
    DEP DATE,
    RESV_NAME_ID INT,
    ROOM_REVENUE DECIMAL(18, 2),
    -- ROOM_REVENUE_1 DECIMAL(18, 2),
    FOOD_REVENUE DECIMAL(18, 2),
    -- PACKAGE_ROOM_REVENUE DECIMAL(18, 2),
    -- PACKAGE_FOOD_REVENUE DECIMAL(18, 2),
    -- TOTAL_PACKAGE_REVENUE DECIMAL(18, 2),
    OTHER_REVENUE DECIMAL(18, 2),
    -- PACKAGE_OTHER_REVENUE DECIMAL(18, 2),
    -- NON_REVENUE DECIMAL(18, 2),
    -- PACKAGE_NON_REVENUE DECIMAL(18, 2),
    -- TOTAL_NON_REVENUE_TAX DECIMAL(18, 2),
    -- PR_ROOM_REVENUE DECIMAL(18, 2),
    -- PR_FOOD_REVENUE DECIMAL(18, 2),
    -- PR_PACKAGE_ROOM_REVENUE DECIMAL(18, 2),
    -- PR_PACKAGE_FOOD_REVENUE DECIMAL(18, 2),
    -- PR_TOTAL_PACKAGE_REVENUE DECIMAL(18, 2),
    -- PR_TOTAL_REVENUE DECIMAL(18, 2),
    -- PR_OTHER_REVENUE DECIMAL(18, 2),
    -- PR_PACKAGE_OTHER_REVENUE DECIMAL(18, 2),
    -- PR_NON_REVENUE DECIMAL(18, 2),
    -- PR_PACKAGE_NON_REVENUE DECIMAL(18, 2),
    -- PR_TOTAL_NON_REVENUE_TAX DECIMAL(18, 2),
    -- CASH_ROOM_REVENUE DECIMAL(18, 2),
    COMP_ROOM_REVENUE DECIMAL(18, 2),

    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    FILE_NAME NVARCHAR(500)
);

SELECT PROPERTY, REPORT_DATE, COUNT(*) AS NB_ROWS
FROM bim_report.stg.booking_pace_cpv
GROUP BY PROPERTY, REPORT_DATE
ORDER BY PROPERTY, REPORT_DATE

SELECT TOP(100) * FROM bim_report.stg.booking_pace_cpv

INSERT INTO dbo.booking_pace_detail
SELECT REPORT_DATE, FORMAT(CONSIDERED_DATE, 'yyyy-MM') AS STAY_MONTH, PROPERTY, 
ARR AS ARRIVAL, DEP AS DEPARTURE, CONSIDERED_DATE AS STAYING, CREATED_DATE AS CREATE_DATE,
MARKET_CODE AS MARKET, RATE_CODE, NULL AS RATE_AMT, 
ISNULL(ARR, 0) + ISNULL(ROOM_REVENUE, 0) + ISNULL(FOOD_REVENUE, 0) + ISNULL(OTHER_REVENUE, 0) AS TOTAL_TURN_OVER, 
NULL AS ARR, ROOM_REVENUE AS ROOM_REV, FOOD_REVENUE AS FB_REV, OTHER_REVENUE AS OTHER_REV,
NULL AS [STATUS], NULL AS R_TYPE, NULL AS R_CHARGE,
NO_ROOMS AS N_OF_ROOM, ADULTS AS N_OF_ADT, CHILDREN AS N_OF_CHD, 
SOURCE_CODE AS BK_SOURCE, COUNTRY, COUNTRY AS NATIONALITY, CREATED_AT, MODIFIED_AT, FILE_NAME
FROM stg.booking_pace_cpv