-- DROP TABLE stg.booking_pace_opera_01;
-- TRUNCATE TABLE stg.booking_pace_opera_01;
-- DROP TABLE stg.booking_pace_opera_01;
CREATE TABLE stg.booking_pace_opera_01 (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    REPORT_DATE DATE,
    PROPERTY NVARCHAR(50),
    CONSIDERED_DATE DATE,
    ADULTS INT,
    CHILDREN INT,
    CREATED_DATE DATE,
    CREATED_USER NVARCHAR(50),
    COUNTRY NVARCHAR(10),
    NO_ROOMS INT,
    DEDUCT_YN CHAR(1),
    GROUP_YN CHAR(1),
    ROOM_REVENUE DECIMAL(18, 2),
    RATE_USD FLOAT,
    MARKET_CODE NVARCHAR(20),
    SOURCE_CODE NVARCHAR(20),
    CHANNEL NVARCHAR(20),
    RATE_CODE NVARCHAR(20),
    ROOM_CAT NVARCHAR(20),
    RTC NVARCHAR(20),
    ARR DATE,
    DEP DATE,
    RESV_NAME_ID INT,
    ROOM_REVENUE_1 DECIMAL(18, 2),
    FOOD_REVENUE DECIMAL(18, 2),
    PACKAGE_ROOM_REVENUE DECIMAL(18, 2),
    PACKAGE_FOOD_REVENUE DECIMAL(18, 2),
    TOTAL_PACKAGE_REVENUE DECIMAL(18, 2),
    OTHER_REVENUE DECIMAL(18, 2),
    PACKAGE_OTHER_REVENUE DECIMAL(18, 2),
    NON_REVENUE DECIMAL(18, 2),
    PACKAGE_NON_REVENUE DECIMAL(18, 2),
    TOTAL_NON_REVENUE_TAX DECIMAL(18, 2),
    PR_ROOM_REVENUE DECIMAL(18, 2),
    PR_FOOD_REVENUE DECIMAL(18, 2),
    PR_PACKAGE_ROOM_REVENUE DECIMAL(18, 2),
    PR_PACKAGE_FOOD_REVENUE DECIMAL(18, 2),
    PR_TOTAL_PACKAGE_REVENUE DECIMAL(18, 2),
    PR_TOTAL_REVENUE DECIMAL(18, 2),
    PR_OTHER_REVENUE DECIMAL(18, 2),
    PR_PACKAGE_OTHER_REVENUE DECIMAL(18, 2),
    PR_NON_REVENUE DECIMAL(18, 2),
    PR_PACKAGE_NON_REVENUE DECIMAL(18, 2),
    PR_TOTAL_NON_REVENUE_TAX DECIMAL(18, 2),
    CASH_ROOM_REVENUE DECIMAL(18, 2),
    COMP_ROOM_REVENUE DECIMAL(18, 2),

    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME
);

SELECT PROPERTY, REPORT_DATE, COUNT(*) AS NB_ROWS
FROM bim_report.stg.booking_pace_opera_01
GROUP BY PROPERTY, REPORT_DATE

SELECT TOP(100) * FROM bim_report.stg.booking_pace_opera_01